#!/usr/bin/env bash
# Help Function
function showHelp {
    echo "Usage: $0 [manager] [package]"
    echo "  manager: system, flatpak, snap, all"
    echo "  package: package name "
    exit 1
}

# Installer Function
function installPackage {
    local manager="$1"
    local packages="$2"
    echo "##### Installing package with $manager #####"
    echo "##### $packages"
    case $manager in
        APT)
            sudo apt install -y $packages
            ;;
        DNF)
            sudo dnf install -y $packages
            ;;
        ZYPPER)
            sudo zypper install -y $packages
            ;;
        PACMAN)
            sudo pacman -Sy $packages
            ;;
        EOPKG)
            sudo eopkg install -y $packages
            ;;
        PARU)
            paru -Sy --needed $packages
            ;;
        YAY)
            yay -Sy $packages
            ;;
        FLATPAK)
            flatpak install -y $packages
            ;;
        SNAP)
            sudo snap install $packages --classic
            ;;
    esac
}

function trackPackage() {
    local trackerFile=$1
    local packages="$2"
    
    for package in $packages
    do
        if [[ -e "$trackerFile" ]] && [[ "$(cat $trackerFile | grep $package)" == "" ]] || [[ ! -e "$trackerFile" ]]
        then
            echo "$package" >> $systemListFile
        fi  
    done
}

## Define List Files
archListFile=${DEV_MOUNT_POINT}/Configs/my-arch-packages.list
debListFile=${DEV_MOUNT_POINT}/Configs/my-deb-packages.list
rpmListFile=${DEV_MOUNT_POINT}/Configs/my-rpm-packages.list
suseListFile=${DEV_MOUNT_POINT}/Configs/my-suse-packages.list
eopListFile=${DEV_MOUNT_POINT}/Configs/my-eop-packages.list
snapListFile=${DEV_MOUNT_POINT}/Configs/my-snap-packages.list
flpkListFile=${DEV_MOUNT_POINT}/Configs/my-flpk-packages.list

# Check installed Package managers and corresponding List file
systemAppManager=$(findAppMan "system")
if [[ "$systemAppManager" == "APT" ]]; then
    systemListFile="$debListFile"
elif [[ "$systemAppManager" == "DNF" ]]; then
    systemListFile="$rpmListFile"
elif [[ "$systemAppManager" == "ZYPPER" ]]; then
    systemListFile="$suseListFile"
elif [[ "$systemAppManager" == "PACMAN" ]] || [[ "$systemAppManager" == "PARU" ]] || [[ "$systemAppManager" == "YAY" ]]; then
    systemListFile="$archListFile"
elif [[ "$systemAppManager" == "EOPKG" ]]; then
    systemListFile="$eopListFile"
fi

flatpakExist=$(findAppMan "flatpak")
snapExist=$(findAppMan "snap")

# Read CLI Options
manager="$1"
packageName="${@:2}"

# For all install and upgrade
if [[ "$manager" == "all" ]]; then
    # Read System Packages List
    if [[ "$systemAppManager" != "" ]] && [[ -e $systemListFile ]]; then
        systemPackages="$(cat $systemListFile | tr '\n' ' ')"
        installPackage "$systemAppManager" "$systemPackages"
    fi

    # Read Flatpak Packages List
    if [[ "$flatpakExist" != "" ]] && [[ -e $flpkListFile ]]; then
        flatpakPackages="$(cat $flpkListFile | tr '\n' ' ')"
        installPackage "$flatpakExist" "$flatpakPackages"
    fi

    # Read Snap Packages List
    if [[ "$snapExist" != "" ]] && [[ -e $snapListFile ]]; then
        while read snapPackage
        do
            installPackage "$snapExist" "$snapPackage"
        done <<<$(cat $snapListFile)
    fi

# For Flatpak
elif [[ "$manager" == "flatpak" ]] && [[ "$flatpakExist" != "" ]]; then
    installPackage "$flatpakExist" "$packageName"
    if [[ $? -eq 0 ]]
    then
        trackPackage $flpkListFile "$packageName"
    fi

# For Snap
elif [[ "$manager" == "snap" ]] && [[ "$snapExist" != "" ]]; then
    installPackage "$snapExist" "$packageName"
    if [[ $? -eq 0 ]]
    then
        trackPackage $snapListFile "$packageName"
    fi

# For System
elif [[ "$manager" == "system" ]] && [[ "$systemAppManager" != "" ]]; then
    installPackage "$systemAppManager" "$packageName"
    if [[ $? -eq 0 ]]
    then
        trackPackage $systemListFile "$packageName"
    fi
fi
