#!/bin/bash
OS=$(cat /etc/os-release | grep "ID_LIKE=" | cut -d= -f2 | sed 's/"//g')
if [[ "$OS" == "arch" ]]
then
    wget https://mega.nz/linux/repo/Arch_Extra/x86_64/megasync-x86_64.pkg.tar.zst -O /tmp/megasync-x86_64.pkg.tar.zst && sudo pacman -U "/tmp/megasync-x86_64.pkg.tar.zst"
fi
