name: freak-ollama
networks:
  default:
    name: freak-ollama-net
services:
  # Add extra commands which can be run on this service through compose app runner
  ollama:
    annotations:
      extracmd-pull: ollama pull {##}
      extracmddesc-pull: Pull a model from Ollama registry
      extracmd-list: ollama list
      extracmddesc-list: List available models
      extracmd-ps: ollama ps
      extracmddesc-ps: List running models
      extracmd-kill: ollama stop {##}
      extracmddesc-kill: Kill a running model
      extracmd-run: ollama run {##}
      extracmddesc-run: Run and Model and start chat
    image: docker.io/ollama/ollama:latest
    container_name: freak-ollama-ollama
    environment:
      OLLAMA_DEBUG: "1"
      OLLAMA_API_KEY: ${OLLAMA_API_KEY:-}
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -c ':> /dev/tcp/127.0.0.1/11434'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "11434:11434"
    volumes:
      - ${DEV_MOUNT_POINT}/System/ContainerVolumes/OLLAMA:/root/.ollama
      - ${DEV_MOUNT_POINT}/System/ContainerVolumes/OLLAMA/USERSSH:/root/.ssh
